<?php

namespace platform\platformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AppartenirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppartenirRepository extends EntityRepository
{
}
